export const images = {
    home: require('../assets/images/home.png'),
    article: require('../assets/images/article.png'),
    user: require('../assets/images/user.png'),
    heart: require('../assets/images/heart.png'),
    solar_bill: require('../assets/images/solar_bill.png'),
    splash: require('../assets/images/Splash.png'),
    registerScreenBg: require('../assets/images/RegisterScreen.png'),
    google: require('../assets/images/google.png'),
    facebook: require('../assets/images/facebook.png'),
    apple: require('../assets/images/apple.png'),
    eye_off: require('../assets/images/eye-off.png'),
    eye: require('../assets/images/eye.png'),
    right: require('../assets/images/right.png'),
    back_icon: require('../assets/images/Back.png'),
    calender: require('../assets/images/calender.png'),
    down: require('../assets/images/down.png'),
    search: require('../assets/images/searchicon.png'),
    check: require('../assets/images/check.png'),
    edit: require('../assets/images/edit.png'),
    down_arrow: require('../assets/images/down_arrow.png'),
    flag: require('../assets/images/flag.png'),
    logo: require('../assets/images/logo.png'),
    logo_v1: require('../assets/images/logo_v01.png'),
    right_check: require('../assets/images/rightCheck.png'),
    radio_check: require('../assets/images/radio-check.png'),
    radio: require('../assets/images/radio.png'),
    filter: require('../assets/images/filter.png'),
    search_black: require('../assets/images/search.png'),
    notification: require('../assets/images/notification.png'),
    approved: require('../assets/images/approved.png'),
    expnad: require('../assets/images/expand.png'),
    bookmark: require('../assets/images/Bookmark.png'),
    like: require('../assets/images/like.png'),
    id: require('../assets/images/id.png'),
    date: require('../assets/images/date.png'),

    cross: require('../assets/images/cross.png'),
    bookmarks2: require('../assets/images/bookmarks2.png'),
    heart2: require('../assets/images/heart2.png'),
    email2: require('../assets/images/mage_email.png'),
    back_2: require('../assets/images/back2.png'),

    liked: require('../assets/images/liked.png'),
    disliked: require('../assets/images/disliked.png'),
    nutral: require('../assets/images/nutral.png'),
};
