export const images = {
    home: require('../assets/images/home.png'),
    article: require('../assets/images/article.png'),
    user: require('../assets/images/user.png'),
    heart: require('../assets/images/heart.png'),
    solar_bill: require('../assets/images/solar_bill.png'),
    splash: require('../assets/images/Splash.png'),
    registerScreenBg: require('../assets/images/RegisterScreen.png'),
    google: require('../assets/images/google.png'),
    facebook: require('../assets/images/facebook.png'),
    apple: require('../assets/images/apple.png'),
    eye_off: require('../assets/images/eye-off.png'),
    eye: require('../assets/images/eye.png'),
    right: require('../assets/images/right.png'),
    back_icon: require('../assets/images/Back.png'),
    calender: require('../assets/images/calender.png'),
    down: require('../assets/images/down.png'),
    search: require('../assets/images/searchicon.png'),
    check: require('../assets/images/check.png'),
    edit: require('../assets/images/edit.png'),
    down_arrow: require('../assets/images/down_arrow.png'),
    flag: require('../assets/images/flag.png'),
    logo: require('../assets/images/logo.png'),
};